# Generated by Django 3.0.3 on 2020-03-08 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BaseInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_now=True)),
                ('create_at', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='images')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_at', models.DateField(auto_now=True)),
                ('create_at', models.DateField(auto_now=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('baseinformationmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.BaseInformationModel')),
                ('departmental', models.SmallIntegerField(blank=True, null=True)),
            ],
            bases=('model.baseinformationmodel',),
        ),
        migrations.CreateModel(
            name='Practices',
            fields=[
                ('baseinformationmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.BaseInformationModel')),
            ],
            bases=('model.baseinformationmodel',),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('baseinformationmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='model.BaseInformationModel')),
            ],
            bases=('model.baseinformationmodel',),
        ),
    ]
